// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Model;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(TodosAppContext))]
    [Migration("20240113135311_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("api.Model.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("417ac2a7-0fc2-452c-864c-ad4736f8717f"),
                            Content = "Zrob pranie",
                            IsCompleted = false,
                            UserId = new Guid("7ee9c475-e8ee-4e98-abc3-0277c83c5f1e")
                        },
                        new
                        {
                            Id = new Guid("ac2e8133-1826-4e52-ace4-80231ee9a7a1"),
                            Content = "Wyrzuc smieci",
                            IsCompleted = true,
                            UserId = new Guid("7ee9c475-e8ee-4e98-abc3-0277c83c5f1e")
                        });
                });

            modelBuilder.Entity("api.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ee9c475-e8ee-4e98-abc3-0277c83c5f1e"),
                            Password = "123123123",
                            Username = "wladyslaw"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
